name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      couchdb:
        image: couchdb
        ports:
          - 5984:5984
        env:
          COUCHDB_USER: admin
          COUCHDB_PASSWORD: 123456

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install

      - name: Compile TypeScript
        run: tsc -p tsconfig.json

      - name: CouchDB setup
        run: |
          curl -X GET http://admin:123456@127.0.0.1:5984
          curl -X PUT http://admin:123456@127.0.0.1:5984/casbin
          curl -X PUT http://admin:123456@127.0.0.1:5984/casbin/policies -d '{ "_id":"policies", "value":[] }'

      - name: Run tests
        run: npm test

      - name: Coveralls Parallel
        uses: coverallsapp/github-action@v2
        with:
          parallel: true
          github-token: ${{ secrets.github_token }}

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
          github-token: ${{ secrets.github_token }}
